version: "3.8"

services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app_php
    working_dir: /var/www/
    volumes:
      - ./app:/var/www/
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:latest
    container_name: app_nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  postgres:
    image: postgres:latest
    container_name: app_postgres
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: app_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
