nelmio_api_doc:
    documentation:
        info:
            title: Users Symfony App
            description: This is an awesome Symfony app!
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
